# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_param tcl.collectionResultDisplayLimit 0
create_project -in_memory -part xc7z045ffg900-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/oleniuk/project_5/project_5.cache/wt [current_project]
set_property parent.project_path /home/oleniuk/project_5/project_5.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part xilinx.com:zc706:part0:1.3 [current_project]
set_property ip_repo_paths /home/oleniuk/Xilinx_projects/VHDL/pix_shifter [current_project]
set_property ip_output_repo /home/oleniuk/project_5/project_5.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files /home/oleniuk/Xilinx_projects/BRAM_coe_files/img_face_bram1.coe
add_files /home/oleniuk/Xilinx_projects/BRAM_coe_files/img_face_bram2.coe
add_files /home/oleniuk/Xilinx_projects/BRAM_coe_files/img_face_bram3.coe
add_files /home/oleniuk/Xilinx_projects/BRAM_coe_files/img_face_bram4.coe
add_files /home/oleniuk/Xilinx_projects/BRAM_coe_files/img_face_bram5.coe
add_files /home/oleniuk/Xilinx_projects/BRAM_coe_files/img_face_bram6.coe
add_files /home/oleniuk/Xilinx_projects/BRAM_coe_files/ker_coeff_test_1_0.coe
add_files /home/oleniuk/Xilinx_projects/BRAM_coe_files/ker_coeff_real.coe
read_vhdl -library xil_defaultlib /home/oleniuk/project_5/project_5.srcs/sources_1/bd/base_zynq/hdl/base_zynq_wrapper.vhd
add_files /home/oleniuk/project_5/project_5.srcs/sources_1/bd/base_zynq/base_zynq.bd
set_property used_in_implementation false [get_files -all /home/oleniuk/project_5/project_5.srcs/sources_1/bd/base_zynq/ip/base_zynq_processing_system7_0_0/base_zynq_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/oleniuk/project_5/project_5.srcs/sources_1/bd/base_zynq/ip/base_zynq_axi_gpio_0_0/base_zynq_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/oleniuk/project_5/project_5.srcs/sources_1/bd/base_zynq/ip/base_zynq_axi_gpio_0_0/base_zynq_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/oleniuk/project_5/project_5.srcs/sources_1/bd/base_zynq/ip/base_zynq_axi_gpio_0_0/base_zynq_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/oleniuk/project_5/project_5.srcs/sources_1/bd/base_zynq/ip/base_zynq_rst_ps7_0_50M_0/base_zynq_rst_ps7_0_50M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/oleniuk/project_5/project_5.srcs/sources_1/bd/base_zynq/ip/base_zynq_rst_ps7_0_50M_0/base_zynq_rst_ps7_0_50M_0.xdc]
set_property used_in_implementation false [get_files -all /home/oleniuk/project_5/project_5.srcs/sources_1/bd/base_zynq/ip/base_zynq_rst_ps7_0_50M_0/base_zynq_rst_ps7_0_50M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/oleniuk/project_5/project_5.srcs/sources_1/bd/base_zynq/ip/base_zynq_axi_gpio_1_0/base_zynq_axi_gpio_1_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/oleniuk/project_5/project_5.srcs/sources_1/bd/base_zynq/ip/base_zynq_axi_gpio_1_0/base_zynq_axi_gpio_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/oleniuk/project_5/project_5.srcs/sources_1/bd/base_zynq/ip/base_zynq_axi_gpio_1_0/base_zynq_axi_gpio_1_0.xdc]
set_property used_in_implementation false [get_files -all /home/oleniuk/project_5/project_5.srcs/sources_1/bd/base_zynq/ip/base_zynq_axi_gpio_1_2/base_zynq_axi_gpio_1_2_board.xdc]
set_property used_in_implementation false [get_files -all /home/oleniuk/project_5/project_5.srcs/sources_1/bd/base_zynq/ip/base_zynq_axi_gpio_1_2/base_zynq_axi_gpio_1_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/oleniuk/project_5/project_5.srcs/sources_1/bd/base_zynq/ip/base_zynq_axi_gpio_1_2/base_zynq_axi_gpio_1_2.xdc]
set_property used_in_implementation false [get_files -all /home/oleniuk/project_5/project_5.srcs/sources_1/bd/base_zynq/ip/base_zynq_ila_0_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all /home/oleniuk/project_5/project_5.srcs/sources_1/bd/base_zynq/ip/base_zynq_ila_0_0/base_zynq_ila_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/oleniuk/project_5/project_5.srcs/sources_1/bd/base_zynq/ip/base_zynq_xbar_1/base_zynq_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/oleniuk/project_5/project_5.srcs/sources_1/bd/base_zynq/ip/base_zynq_blk_mem_gen_0_0/base_zynq_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/oleniuk/project_5/project_5.srcs/sources_1/bd/base_zynq/ip/base_zynq_blk_mem_gen_0_3/base_zynq_blk_mem_gen_0_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/oleniuk/project_5/project_5.srcs/sources_1/bd/base_zynq/ip/base_zynq_blk_mem_gen_1_0/base_zynq_blk_mem_gen_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/oleniuk/project_5/project_5.srcs/sources_1/bd/base_zynq/ip/base_zynq_blk_mem_gen_2_1/base_zynq_blk_mem_gen_2_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/oleniuk/project_5/project_5.srcs/sources_1/bd/base_zynq/ip/base_zynq_blk_mem_gen_3_1/base_zynq_blk_mem_gen_3_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/oleniuk/project_5/project_5.srcs/sources_1/bd/base_zynq/ip/base_zynq_blk_mem_gen_4_1/base_zynq_blk_mem_gen_4_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/oleniuk/project_5/project_5.srcs/sources_1/bd/base_zynq/ip/base_zynq_axi_bram_ctrl_0_0/base_zynq_axi_bram_ctrl_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/oleniuk/project_5/project_5.srcs/sources_1/bd/base_zynq/ip/base_zynq_blk_mem_gen_5_0/base_zynq_blk_mem_gen_5_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/oleniuk/project_5/project_5.srcs/sources_1/bd/base_zynq/ip/base_zynq_axi_bram_ctrl_0_3/base_zynq_axi_bram_ctrl_0_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/oleniuk/project_5/project_5.srcs/sources_1/bd/base_zynq/ip/base_zynq_axi_bram_ctrl_1_0/base_zynq_axi_bram_ctrl_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/oleniuk/project_5/project_5.srcs/sources_1/bd/base_zynq/ip/base_zynq_axi_bram_ctrl_2_1/base_zynq_axi_bram_ctrl_2_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/oleniuk/project_5/project_5.srcs/sources_1/bd/base_zynq/ip/base_zynq_axi_bram_ctrl_3_1/base_zynq_axi_bram_ctrl_3_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/oleniuk/project_5/project_5.srcs/sources_1/bd/base_zynq/ip/base_zynq_axi_bram_ctrl_4_1/base_zynq_axi_bram_ctrl_4_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/oleniuk/project_5/project_5.srcs/sources_1/bd/base_zynq/ip/base_zynq_axi_bram_ctrl_5_1/base_zynq_axi_bram_ctrl_5_1_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/oleniuk/project_5/project_5.srcs/sources_1/bd/base_zynq/ip/base_zynq_auto_ds_8/base_zynq_auto_ds_8_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/oleniuk/project_5/project_5.srcs/sources_1/bd/base_zynq/ip/base_zynq_auto_ds_8/base_zynq_auto_ds_8_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/oleniuk/project_5/project_5.srcs/sources_1/bd/base_zynq/ip/base_zynq_auto_ds_8/base_zynq_auto_ds_8_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/oleniuk/project_5/project_5.srcs/sources_1/bd/base_zynq/ip/base_zynq_auto_pc_2/base_zynq_auto_pc_2_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/oleniuk/project_5/project_5.srcs/sources_1/bd/base_zynq/ip/base_zynq_auto_ds_7/base_zynq_auto_ds_7_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/oleniuk/project_5/project_5.srcs/sources_1/bd/base_zynq/ip/base_zynq_auto_ds_7/base_zynq_auto_ds_7_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/oleniuk/project_5/project_5.srcs/sources_1/bd/base_zynq/ip/base_zynq_auto_ds_7/base_zynq_auto_ds_7_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/oleniuk/project_5/project_5.srcs/sources_1/bd/base_zynq/ip/base_zynq_auto_pc_1/base_zynq_auto_pc_1_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/oleniuk/project_5/project_5.srcs/sources_1/bd/base_zynq/ip/base_zynq_auto_ds_6/base_zynq_auto_ds_6_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/oleniuk/project_5/project_5.srcs/sources_1/bd/base_zynq/ip/base_zynq_auto_ds_6/base_zynq_auto_ds_6_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/oleniuk/project_5/project_5.srcs/sources_1/bd/base_zynq/ip/base_zynq_auto_ds_6/base_zynq_auto_ds_6_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/oleniuk/project_5/project_5.srcs/sources_1/bd/base_zynq/ip/base_zynq_auto_ds_5/base_zynq_auto_ds_5_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/oleniuk/project_5/project_5.srcs/sources_1/bd/base_zynq/ip/base_zynq_auto_ds_5/base_zynq_auto_ds_5_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/oleniuk/project_5/project_5.srcs/sources_1/bd/base_zynq/ip/base_zynq_auto_ds_5/base_zynq_auto_ds_5_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/oleniuk/project_5/project_5.srcs/sources_1/bd/base_zynq/ip/base_zynq_auto_ds_4/base_zynq_auto_ds_4_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/oleniuk/project_5/project_5.srcs/sources_1/bd/base_zynq/ip/base_zynq_auto_ds_4/base_zynq_auto_ds_4_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/oleniuk/project_5/project_5.srcs/sources_1/bd/base_zynq/ip/base_zynq_auto_ds_4/base_zynq_auto_ds_4_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/oleniuk/project_5/project_5.srcs/sources_1/bd/base_zynq/ip/base_zynq_auto_ds_3/base_zynq_auto_ds_3_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/oleniuk/project_5/project_5.srcs/sources_1/bd/base_zynq/ip/base_zynq_auto_ds_3/base_zynq_auto_ds_3_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/oleniuk/project_5/project_5.srcs/sources_1/bd/base_zynq/ip/base_zynq_auto_ds_3/base_zynq_auto_ds_3_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/oleniuk/project_5/project_5.srcs/sources_1/bd/base_zynq/ip/base_zynq_auto_ds_2/base_zynq_auto_ds_2_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/oleniuk/project_5/project_5.srcs/sources_1/bd/base_zynq/ip/base_zynq_auto_ds_2/base_zynq_auto_ds_2_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/oleniuk/project_5/project_5.srcs/sources_1/bd/base_zynq/ip/base_zynq_auto_ds_2/base_zynq_auto_ds_2_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/oleniuk/project_5/project_5.srcs/sources_1/bd/base_zynq/ip/base_zynq_auto_ds_1/base_zynq_auto_ds_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/oleniuk/project_5/project_5.srcs/sources_1/bd/base_zynq/ip/base_zynq_auto_ds_1/base_zynq_auto_ds_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/oleniuk/project_5/project_5.srcs/sources_1/bd/base_zynq/ip/base_zynq_auto_ds_1/base_zynq_auto_ds_1_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/oleniuk/project_5/project_5.srcs/sources_1/bd/base_zynq/ip/base_zynq_auto_ds_0/base_zynq_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/oleniuk/project_5/project_5.srcs/sources_1/bd/base_zynq/ip/base_zynq_auto_ds_0/base_zynq_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/oleniuk/project_5/project_5.srcs/sources_1/bd/base_zynq/ip/base_zynq_auto_ds_0/base_zynq_auto_ds_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/oleniuk/project_5/project_5.srcs/sources_1/bd/base_zynq/ip/base_zynq_auto_pc_0/base_zynq_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/oleniuk/project_5/project_5.srcs/sources_1/bd/base_zynq/ip/base_zynq_auto_pc_3/base_zynq_auto_pc_3_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/oleniuk/project_5/project_5.srcs/sources_1/bd/base_zynq/ip/base_zynq_auto_us_0/base_zynq_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/oleniuk/project_5/project_5.srcs/sources_1/bd/base_zynq/ip/base_zynq_auto_us_0/base_zynq_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/oleniuk/project_5/project_5.srcs/sources_1/bd/base_zynq/ip/base_zynq_auto_us_0/base_zynq_auto_us_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/oleniuk/project_5/project_5.srcs/sources_1/bd/base_zynq/base_zynq_ooc.xdc]
set_property is_locked true [get_files /home/oleniuk/project_5/project_5.srcs/sources_1/bd/base_zynq/base_zynq.bd]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top base_zynq_wrapper -part xc7z045ffg900-2


write_checkpoint -force -noxdef base_zynq_wrapper.dcp

catch { report_utilization -file base_zynq_wrapper_utilization_synth.rpt -pb base_zynq_wrapper_utilization_synth.pb }
