# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/base_zynq/base_zynq.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq || ORIG_REF_NAME==base_zynq}]

# IP: bd/base_zynq/ip/base_zynq_processing_system7_0_0/base_zynq_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_processing_system7_0_0 || ORIG_REF_NAME==base_zynq_processing_system7_0_0}]

# IP: bd/base_zynq/ip/base_zynq_axi_gpio_0_0/base_zynq_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_axi_gpio_0_0 || ORIG_REF_NAME==base_zynq_axi_gpio_0_0}]

# IP: bd/base_zynq/ip/base_zynq_ps7_0_axi_periph_0/base_zynq_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_ps7_0_axi_periph_0 || ORIG_REF_NAME==base_zynq_ps7_0_axi_periph_0}]

# IP: bd/base_zynq/ip/base_zynq_rst_ps7_0_50M_0/base_zynq_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_rst_ps7_0_50M_0 || ORIG_REF_NAME==base_zynq_rst_ps7_0_50M_0}]

# IP: bd/base_zynq/ip/base_zynq_fsm_bram_addr_pix_ker_0_0/base_zynq_fsm_bram_addr_pix_ker_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_fsm_bram_addr_pix_ker_0_0 || ORIG_REF_NAME==base_zynq_fsm_bram_addr_pix_ker_0_0}]

# IP: bd/base_zynq/ip/base_zynq_axi_gpio_1_0/base_zynq_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_axi_gpio_1_0 || ORIG_REF_NAME==base_zynq_axi_gpio_1_0}]

# IP: bd/base_zynq/ip/base_zynq_xlslice_2_1/base_zynq_xlslice_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_xlslice_2_1 || ORIG_REF_NAME==base_zynq_xlslice_2_1}]

# IP: bd/base_zynq/ip/base_zynq_xlslice_7_0/base_zynq_xlslice_7_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_xlslice_7_0 || ORIG_REF_NAME==base_zynq_xlslice_7_0}]

# IP: bd/base_zynq/ip/base_zynq_xlslice_8_0/base_zynq_xlslice_8_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_xlslice_8_0 || ORIG_REF_NAME==base_zynq_xlslice_8_0}]

# IP: bd/base_zynq/ip/base_zynq_axi_gpio_1_2/base_zynq_axi_gpio_1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_axi_gpio_1_2 || ORIG_REF_NAME==base_zynq_axi_gpio_1_2}]

# IP: bd/base_zynq/ip/base_zynq_ila_0_0/base_zynq_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_ila_0_0 || ORIG_REF_NAME==base_zynq_ila_0_0}]

# IP: bd/base_zynq/ip/base_zynq_util_vector_logic_1_0/base_zynq_util_vector_logic_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_util_vector_logic_1_0 || ORIG_REF_NAME==base_zynq_util_vector_logic_1_0}]

# IP: bd/base_zynq/ip/base_zynq_xbar_1/base_zynq_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_xbar_1 || ORIG_REF_NAME==base_zynq_xbar_1}]

# IP: bd/base_zynq/ip/base_zynq_blk_mem_gen_0_0/base_zynq_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_blk_mem_gen_0_0 || ORIG_REF_NAME==base_zynq_blk_mem_gen_0_0}]

# IP: bd/base_zynq/ip/base_zynq_blk_mem_gen_0_3/base_zynq_blk_mem_gen_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_blk_mem_gen_0_3 || ORIG_REF_NAME==base_zynq_blk_mem_gen_0_3}]

# IP: bd/base_zynq/ip/base_zynq_blk_mem_gen_1_0/base_zynq_blk_mem_gen_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_blk_mem_gen_1_0 || ORIG_REF_NAME==base_zynq_blk_mem_gen_1_0}]

# IP: bd/base_zynq/ip/base_zynq_blk_mem_gen_2_1/base_zynq_blk_mem_gen_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_blk_mem_gen_2_1 || ORIG_REF_NAME==base_zynq_blk_mem_gen_2_1}]

# IP: bd/base_zynq/ip/base_zynq_blk_mem_gen_3_1/base_zynq_blk_mem_gen_3_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_blk_mem_gen_3_1 || ORIG_REF_NAME==base_zynq_blk_mem_gen_3_1}]

# IP: bd/base_zynq/ip/base_zynq_blk_mem_gen_4_1/base_zynq_blk_mem_gen_4_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_blk_mem_gen_4_1 || ORIG_REF_NAME==base_zynq_blk_mem_gen_4_1}]

# IP: bd/base_zynq/ip/base_zynq_axi_bram_ctrl_0_0/base_zynq_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_axi_bram_ctrl_0_0 || ORIG_REF_NAME==base_zynq_axi_bram_ctrl_0_0}]

# IP: bd/base_zynq/ip/base_zynq_blk_mem_gen_5_0/base_zynq_blk_mem_gen_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_blk_mem_gen_5_0 || ORIG_REF_NAME==base_zynq_blk_mem_gen_5_0}]

# IP: bd/base_zynq/ip/base_zynq_axi_bram_ctrl_0_3/base_zynq_axi_bram_ctrl_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_axi_bram_ctrl_0_3 || ORIG_REF_NAME==base_zynq_axi_bram_ctrl_0_3}]

# IP: bd/base_zynq/ip/base_zynq_axi_bram_ctrl_1_0/base_zynq_axi_bram_ctrl_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_axi_bram_ctrl_1_0 || ORIG_REF_NAME==base_zynq_axi_bram_ctrl_1_0}]

# IP: bd/base_zynq/ip/base_zynq_axi_bram_ctrl_2_1/base_zynq_axi_bram_ctrl_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_axi_bram_ctrl_2_1 || ORIG_REF_NAME==base_zynq_axi_bram_ctrl_2_1}]

# IP: bd/base_zynq/ip/base_zynq_axi_bram_ctrl_3_1/base_zynq_axi_bram_ctrl_3_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_axi_bram_ctrl_3_1 || ORIG_REF_NAME==base_zynq_axi_bram_ctrl_3_1}]

# IP: bd/base_zynq/ip/base_zynq_axi_bram_ctrl_4_1/base_zynq_axi_bram_ctrl_4_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_axi_bram_ctrl_4_1 || ORIG_REF_NAME==base_zynq_axi_bram_ctrl_4_1}]

# IP: bd/base_zynq/ip/base_zynq_axi_bram_ctrl_5_1/base_zynq_axi_bram_ctrl_5_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_axi_bram_ctrl_5_1 || ORIG_REF_NAME==base_zynq_axi_bram_ctrl_5_1}]

# IP: bd/base_zynq/ip/base_zynq_auto_ds_8/base_zynq_auto_ds_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_auto_ds_8 || ORIG_REF_NAME==base_zynq_auto_ds_8}]

# IP: bd/base_zynq/ip/base_zynq_auto_pc_2/base_zynq_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_auto_pc_2 || ORIG_REF_NAME==base_zynq_auto_pc_2}]

# IP: bd/base_zynq/ip/base_zynq_auto_ds_7/base_zynq_auto_ds_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_auto_ds_7 || ORIG_REF_NAME==base_zynq_auto_ds_7}]

# IP: bd/base_zynq/ip/base_zynq_auto_pc_1/base_zynq_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_auto_pc_1 || ORIG_REF_NAME==base_zynq_auto_pc_1}]

# IP: bd/base_zynq/ip/base_zynq_auto_ds_6/base_zynq_auto_ds_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_auto_ds_6 || ORIG_REF_NAME==base_zynq_auto_ds_6}]

# IP: bd/base_zynq/ip/base_zynq_auto_ds_5/base_zynq_auto_ds_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_auto_ds_5 || ORIG_REF_NAME==base_zynq_auto_ds_5}]

# IP: bd/base_zynq/ip/base_zynq_auto_ds_4/base_zynq_auto_ds_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_auto_ds_4 || ORIG_REF_NAME==base_zynq_auto_ds_4}]

# IP: bd/base_zynq/ip/base_zynq_auto_ds_3/base_zynq_auto_ds_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_auto_ds_3 || ORIG_REF_NAME==base_zynq_auto_ds_3}]

# IP: bd/base_zynq/ip/base_zynq_auto_ds_2/base_zynq_auto_ds_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_auto_ds_2 || ORIG_REF_NAME==base_zynq_auto_ds_2}]

# IP: bd/base_zynq/ip/base_zynq_auto_ds_1/base_zynq_auto_ds_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_auto_ds_1 || ORIG_REF_NAME==base_zynq_auto_ds_1}]

# IP: bd/base_zynq/ip/base_zynq_auto_ds_0/base_zynq_auto_ds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_auto_ds_0 || ORIG_REF_NAME==base_zynq_auto_ds_0}]

# IP: bd/base_zynq/ip/base_zynq_auto_pc_0/base_zynq_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_auto_pc_0 || ORIG_REF_NAME==base_zynq_auto_pc_0}]

# IP: bd/base_zynq/ip/base_zynq_auto_pc_3/base_zynq_auto_pc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_auto_pc_3 || ORIG_REF_NAME==base_zynq_auto_pc_3}]

# IP: bd/base_zynq/ip/base_zynq_auto_us_0/base_zynq_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_auto_us_0 || ORIG_REF_NAME==base_zynq_auto_us_0}]

# XDC: bd/base_zynq/base_zynq_ooc.xdc
